[versions]
agp = "8.11.2"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.2.1"
picasso = "2.71828"
playServicesMlkitDocumentScanner = "16.0.0"
sqliteAndroid = "3.45.3"
documentfile = "1.1.0"
tessTwo = "9.1.0"
workRuntime = "2.11.0"
playServicesMlkitTextRecognitionCommon = "19.1.0"
visionCommon = "17.3.0"
playServicesMlkitTextRecognition = "19.0.1"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }
play-services-mlkit-document-scanner = { module = "com.google.android.gms:play-services-mlkit-document-scanner", version.ref = "playServicesMlkitDocumentScanner" }
documentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "documentfile" }
tess-two = { module = "com.rmtheis:tess-two", version.ref = "tessTwo" }
work-runtime = { group = "androidx.work", name = "work-runtime", version.ref = "workRuntime" }
play-services-mlkit-text-recognition-common = { group = "com.google.android.gms", name = "play-services-mlkit-text-recognition-common", version.ref = "playServicesMlkitTextRecognitionCommon" }
vision-common = { group = "com.google.mlkit", name = "vision-common", version.ref = "visionCommon" }
play-services-mlkit-text-recognition = { group = "com.google.android.gms", name = "play-services-mlkit-text-recognition", version.ref = "playServicesMlkitTextRecognition" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

